trigger:
- none

parameters:
  - name: workingDirectory
    type: string
    default: "$(Build.SourcesDirectory)/infra_basica"

  - name: Action
    displayName: Action
    type: string
    default: 'Apply'
    values:
    - Apply
    - Destroy

pool:
  vmImage: ubuntu-latest

stages:
- stage: terraform_install  
  displayName: Terraform Install
  jobs:
  - job: install
    steps:
    - script: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
        terraform --version

- stage: terraform_init  
  displayName: Terraform Init and Validate
  dependsOn: terraform_install
  condition: and(succeeded('terraform_install'), ne('${{ parameters.Action }}', 'Destroy'))
  jobs:
  - job: Init
    steps:
    - task: CmdLine@2
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        script: |
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          terraform --version
          terraform init
          terraform validate

- stage: terraform_plan  
  displayName: Terraform Plan
  dependsOn: terraform_init
  condition: and(succeeded('terraform_init'), ne('${{ parameters.Action }}', 'Destroy'))
  jobs:
  - job: Plan
    steps:
    - task: CmdLine@2
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        script: |
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          terraform --version
          terraform init
          terraform plan

- stage: terraform_apply  
  displayName: Terraform Apply
  dependsOn: terraform_plan
  condition: and(succeeded('terraform_plan'), ne('${{ parameters.Action }}', 'Destroy'), eq('${{ parameters.Action }}', 'Apply'))
  jobs:
  - job: Apply
    steps:
    - task: CmdLine@2
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        script: |
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          terraform --version
          terraform init
          terraform apply -auto-approve

- stage: ansible
  displayName: Ansible
  condition: and(succeeded('terraform_plan'), ne('${{ parameters.Action }}', 'Destroy'), eq('${{ parameters.Action }}', 'Apply'))
  jobs:
  - job: Ansivle_Playbook
    steps:
    - task: Bash@3     
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        targetType: inline  
        script: | 
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) 
          export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          export ANSIBLE_HOST_KEY_CHECKING="False"
          export SSH_KEY=$(cat /home/vsts/work/_temp/chave_privada_gitlab) > /dev/null
          eval $(ssh-agent -s)
          ssh-add /home/vsts/work/_temp/chave_privada_gitlab
          echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
          sudo apt-get update -y
          sudo apt-get install python3 -y
          python3 -m venv .venv && source .venv/bin/activate
          python3 -m pip install ansible boto3 pywinrm
          ansible --version
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.aws_ec2.yml playbook_linux_servers.yml -e ansible_ssh_private_key_file='{{ lookup("env", "SSH_KEY") }}' -v

- stage: terraform_destroy 
  displayName: Terraform Destroy
  dependsOn: terraform_install
  condition: eq('${{ parameters.Action }}', 'Destroy')
  jobs:
  - job: Destroy
    steps:
    - task: CmdLine@2
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        script: |
          export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
          export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
          terraform --version
          terraform init
          terraform destroy -auto-approve